export const NONE       = 'player.status.none'
export const PLAYING    = 'player.status.playing'
export const BUFFERING  = 'player.status.BUFFERING'
export const CONNECTING = 'player.status.connecting'
export const PAUSED     = 'player.status.paused'
export const ENDED      = 'player.status.ended'
